var data = {
    widthChart: 500,
    heightChart: 1000,
    chartName: "BIỂU ĐỒ TỈ LỆ LEVEL OF POSITION",
    listColors: ["#3366cc", "#dc3912", "#ff9900", "#109618"],
    titleFont: "",
    titleColor: "",
    noteFont: "",
    noteColor: "",
    noteStyle: "",
    noteColorSpacing: "",
    donutFont: "",
    donutColor: "",
    donutStart: "",
    donutTop: "",
    donutLeft: "",
    donutHoldSize: "",
    donutSmallFont: "",
    donutSmallColor: "",
    marginTitleToTop: "",
    
    radius: 100,
    listValues: [{ x: 'A', y: 0 },
                { x: 'A', y: 2 },
                { x: 'A', y: 2 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 3 },
                { x: 'B', y: 4 },
                { x: 'B', y: 4 },
                { x: 'B', y: 4 }, ]
};